import time
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from selenium.webdriver.support.select import Select
from selenium.webdriver.support.wait import WebDriverWait
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.support import expected_conditions as EC
driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()))
driver.maximize_window()
driver.get("https://www.saucedemo.com/")
user_name=driver.find_element(By.XPATH,"//input[@id='user-name']")
pass_word=driver.find_element(By.XPATH,"//input[@id='password']")
login_butt=driver.find_element(By.XPATH,"//input[@id='login-button']")
user_name.send_keys("standard_user")
pass_word.send_keys("secret_sauce")
wait=WebDriverWait(driver,10)
wait.until(EC.element_to_be_clickable(login_butt)).click()
time.sleep(4)
wait.until(EC.title_is("Swag Labs"))
add1=driver.find_element(By.XPATH,"//button[@id='add-to-cart-sauce-labs-backpack']")
wait.until(EC.element_to_be_clickable(add1)).click()
menu=driver.find_element(By.XPATH,"//button[@id='react-burger-menu-btn']")
wait.until(EC.element_to_be_clickable(menu)).click()
cross_butt=driver.find_element(By.XPATH,"//button[@id='react-burger-cross-btn']")
wait.until(EC.element_to_be_clickable(cross_butt)).click()
menu=driver.find_element(By.XPATH,"//button[@id='react-burger-menu-btn']")
wait.until(EC.element_to_be_clickable(menu)).click()
logout=driver.find_element(By.XPATH,"//a[@id='logout_sidebar_link']")
wait.until(EC.element_to_be_clickable(logout)).click()
time.sleep(2)
user_name1=driver.find_element(By.XPATH,"//input[@id='user-name']")
pass_word1=driver.find_element(By.XPATH,"//input[@id='password']")
user_name1.send_keys("standard_user")
pass_word1.send_keys("secret_sauce")
login_butt1=driver.find_element(By.XPATH,"//input[@id='login-button']")
wait.until(EC.element_to_be_clickable(login_butt1)).click()
time.sleep(2)
add2=driver.find_element(By.XPATH,"//button[@id='add-to-cart-sauce-labs-bike-light']")
wait.until(EC.element_to_be_clickable(add2)).click()
add3=driver.find_element(By.XPATH,"//button[@id='add-to-cart-test.allthethings()-t-shirt-(red)']")
driver.execute_script("arguments[0].scrollIntoView();",add3 )
wait.until(EC.element_to_be_clickable(add3)).click()
dropdown=driver.find_element(By.XPATH,"//select[@class='product_sort_container']")
select=Select(dropdown)
select.select_by_index(3)
add4=driver.find_element(By.XPATH,"//button[@id='add-to-cart-sauce-labs-onesie']")
wait.until(EC.element_to_be_clickable(add4)).click()
time.sleep(3)
wait.until(EC.element_to_be_clickable((By.CLASS_NAME, "shopping_cart_link"))).click()
continue1=driver.find_element(By.XPATH,"//button[@id='continue-shopping']")
wait.until(EC.element_to_be_clickable(continue1)).click()
wait.until(EC.element_to_be_clickable((By.CLASS_NAME, "shopping_cart_link"))).click()
checkout=driver.find_element(By.XPATH,"//button[@id='checkout']")
wait.until(EC.element_to_be_clickable(checkout)).click()
wait.until(EC.presence_of_element_located((By.XPATH,"//input[@id='first-name']")))
first_name=driver.find_element(By.XPATH,"//input[@id='first-name']")
first_name.send_keys("Asmit")
last_name=driver.find_element(By.XPATH,"//input[@id='last-name']")
last_name.send_keys("kumar")
zipcode=driver.find_element(By.XPATH,"//input[@id='postal-code']")
zipcode.send_keys("123456")
wait.until(EC.element_to_be_clickable((By.XPATH,"//input[@id='continue']"))).click()
total_price=driver.find_element(By.XPATH,"//div[@class='summary_total_label']")
print(total_price.text)
wait.until(EC.element_to_be_clickable((By.XPATH,"//button[@id='finish']"))).click()
assert "Checkout: Complete!" in driver.page_source
print("done sir !!!")
driver.close()
