import time
from selenium import webdriver
from selenium.webdriver import ActionChains
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from selenium.webdriver.support.wait import WebDriverWait
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.support import expected_conditions as EC
driver= webdriver.Chrome(service=Service(ChromeDriverManager().install()))
driver.get("https://automationexercise.com/login")
driver.maximize_window()
login_email=driver.find_element(By.XPATH,"//input[@data-qa='login-email']")
login_email.send_keys("asmitkumar1626@gmail.com")
login_password=driver.find_element(By.XPATH,"//input[@placeholder='Password']")
login_password.send_keys("asmit7750@")
wait=WebDriverWait(driver,10)
wait.until(EC.element_to_be_clickable((By.XPATH,"//button[normalize-space()='Login']"))).click()
img1=driver.find_element(By.XPATH,"//body[1]/section[2]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/img[1]")
driver.execute_script("arguments[0].scrollIntoView();",img1)
wait.until(EC.visibility_of_element_located((By.XPATH,"//body[1]/section[2]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/img[1]")))
actions=ActionChains(driver)
actions.move_to_element(img1).perform()
wait.until(EC.element_to_be_clickable((By.XPATH,"//body[1]/section[2]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/a[1]"))).click()
time.sleep(3)
wait.until(EC.visibility_of_element_located((By.XPATH,"//h4[normalize-space()='Added!']")))
wait.until(EC.element_to_be_clickable((By.XPATH,"//button[normalize-space()='Continue Shopping']"))).click()
img2=driver.find_element(By.XPATH,"//body[1]/section[2]/div[1]/div[1]/div[2]/div[1]/div[3]/div[1]/div[1]/div[1]/img[1]")
actions.move_to_element(img2).perform()
wait.until(EC.element_to_be_clickable((By.XPATH,"//body[1]/section[2]/div[1]/div[1]/div[2]/div[1]/div[3]/div[1]/div[1]/div[2]/div[1]/a[1]"))).click()
wait.until(EC.visibility_of_element_located((By.XPATH,"//h4[normalize-space()='Added!']")))
wait.until(EC.element_to_be_clickable((By.XPATH,"//button[normalize-space()='Continue Shopping']"))).click()
dropdown=driver.find_element(By.XPATH,"//a[normalize-space()='Women']")
actions.move_to_element(dropdown).click().perform()
tops=driver.find_element(By.XPATH,"//a[normalize-space()='Tops']")
wait.until(EC.visibility_of_element_located((By.XPATH,"//a[normalize-space()='Tops']")))
actions.move_to_element(tops).click().perform()
wait.until(EC.presence_of_element_located((By.XPATH,"//h2[normalize-space()='Women - Tops Products']")))
top1=driver.find_element(By.XPATH,"//body[1]/section[1]/div[1]/div[2]/div[2]/div[1]/div[5]/div[1]/div[1]/div[1]/img[1]")
driver.execute_script("arguments[0].scrollIntoView();",top1)
actions.move_to_element(top1).perform()
wait.until(EC.element_to_be_clickable((By.XPATH,"//body[1]/section[1]/div[1]/div[2]/div[2]/div[1]/div[5]/div[1]/div[1]/div[2]/div[1]/a[1]"))).click()
wait.until(EC.visibility_of_element_located((By.XPATH,"//h4[normalize-space()='Added!']")))
wait.until(EC.element_to_be_clickable((By.XPATH,"//button[normalize-space()='Continue Shopping']"))).click()
cart=driver.find_element(By.XPATH,"//body[1]/header[1]/div[1]/div[1]/div[1]/div[2]/div[1]/ul[1]/li[3]/a[1]")
driver.execute_script("arguments[0].scrollIntoView();",cart)
cart.click()
wait.until(EC.title_is("Automation Exercise - Checkout"))
proceed=driver.find_element(By.XPATH,"//a[normalize-space()='Proceed To Checkout']")
wait.until(EC.element_to_be_clickable(proceed)).click()
driver.find_element(By.XPATH,"//textarea[@name='message']").send_keys("very good!!!")
wait.until(EC.element_to_be_clickable((By.XPATH,"//a[normalize-space()='Place Order']"))).click()